---

- name: Install libreoffice
  ansible.builtin.package:
    name: libreoffice
    state: present

- name: Create font family directory
  ansible.builtin.file:
    path: "{{ potos_libreoffice_font_directory }}/{{ item.family }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ potos_libreoffice_fonts }}"
  loop_control:
    label: "{{ item.family | default('No family specified.') }}"
  when:
    - item.family is defined

- name: Install font from url
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ potos_libreoffice_font_directory }}/{{ item.family | default('') }}/{{ item.url | basename | default('') }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ potos_libreoffice_fonts }}"
  loop_control:
    label: "{{ item.url | default('No url specified') }}"
  notify:
    - Builds font information cache files
  when:
    - potos_libreoffice_fonts | length > 0
    - item.url is defined

- name: Install font from package
  ansible.builtin.package:
    name: "{{ item.name }}"
  loop: "{{ potos_libreoffice_fonts }}"
  loop_control:
    label: "{{ item.name | default('No name specified') }}"
  when:
    - potos_libreoffice_fonts | length > 0
    - item.name is defined

- name: Install font from src
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ potos_libreoffice_font_directory }}/{{ item.family | default('') }}/{{ item.src }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ potos_libreoffice_fonts }}"
  loop_control:
    label: "{{ item.src | default('No src specified') }}"
  when:
    - potos_libreoffice_fonts | length > 0
    - item.src is defined

- name: Create libreoffice template directory for specific fonts
  ansible.builtin.file:
    path: "{{ potos_libreoffice_template_directory }}/{{ item.destination_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ potos_libreoffice_templates }}"
  loop_control:
    label: "{{ item.destination_directory | default('No destination directory specified') }}"
  when:
    - item.destination_directory is defined

- name: Install libreoffice template
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ potos_libreoffice_template_directory }}/{{ item.destination_directory | default('') }}/{{ item.name | default(item.url | basename) }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ potos_libreoffice_templates }}"
  loop_control:
    label: "{{ item.name | default(item.url | basename) }}"
  when:
    - potos_libreoffice_templates | length > 0
