---

- name: Converge
  hosts: all
  gather_facts: yes

  tasks:
    - name: Run role
      ansible.builtin.include_role:
        name: ansible-role-potos_libreoffice
      vars:
        potos_libreoffice_templates:
          - url: "https://extensions.libreoffice.org/assets/downloads/1011/1677853134/CV-deux-colonnes-sobre-v2.ott"
          - name: squares.ott
            url: "https://extensions.libreoffice.org/assets/downloads/z/1cm-paper.ott"
            destination_directory: sales
          - src: templates/free_printable_gift_certificate_template.ott
        potos_libreoffice_fonts:
          - name: fonts-open-sans
          - url: "https://github.com/adobe-fonts/source-sans/raw/release/TTF/SourceSans3-Regular.ttf"
            family: source-sans
          - src: EA Sports Covers SC 1.5.ttf
            family: my_fonts
        potos_libreoffice_palettes:
          - name: dracula.soc
            url: "https://raw.githubusercontent.com/dracula/libreoffice/master/dracula.soc"
          - src: palettes/example.soc
