---

- name: Converge
  hosts: all
  gather_facts: yes

  roles:
    - role: ansible-role-potos_libreoffice
      potos_libreoffice_templates:
        - source: "https://extensions.libreoffice.org/assets/downloads/1011/1677853134/CV-deux-colonnes-sobre-v2.ott"
        - name: squares.ott
          source: "https://extensions.libreoffice.org/assets/downloads/z/1cm-paper.ott"
          destination_directory: sales
