---

- name: Prepare
  hosts: all
  gather_facts: yes

  tasks:
    # Update the apt cache as it's potentialy outdated in the container
    - name: Update apt
      ansible.builtin.apt:
        update_cache: yes
